---
title: "2017302360010_张平_R语言作业"
author: "张平"
date: "2019年5月16日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
```

## P10 Q1
### (a)
```{r}
words[str_detect(words, "^x|x$")]
words[str_detect(words, "^x") | str_detect(words, "x$")]
```

### (b) 
```{r}
str_subset(words, "^[aeiou].*[^aeiou]$") %>% head()

words[str_detect(words, "^[aeiou]") & str_detect(words, "[^aeiou]$")] %>% head()
```

### (c)
没有含有全部元音字母的单词.
```{r}
pattern <-
  cross(rerun(5, c("a", "e", "i", "o", "u")),
    .filter = function(...) {
      x <- as.character(unlist(list(...)))
      length(x) != length(unique(x))
    }
  ) %>%
  map_chr(~ str_c(unlist(.x), collapse = ".*")) %>%
  str_c(collapse = "|")
str_subset(words, pattern)

words[str_detect(words, "a") &
      str_detect(words, "e") &
      str_detect(words, "i") &
      str_detect(words, "o") &
      str_detect(words, "u")
      ]
```

---

## P10 Q2
### (a)
"appropriate", "associate", "available", "colleague", "encourage", "experience", "individual", "television"单词含有最多数量的元音字母. 单词"a"含有最大比例的元音字母.
```{r}
most_vowels <- str_count(words, "[aeiou]") 
prop_vowels <- most_vowels / str_length(words)

words[most_vowels == max(most_vowels)]
words[prop_vowels == max(prop_vowels)]
```

---

## P10 Q3
### (a)
```{r}
head(str_extract(sentences, "^[A-Za-z]+\\b"))
```

### (b)
```{r}
word_match <- "\\b[A-Za-z]+ing\\b"
unique(unlist(str_extract_all(sentences, word_match))) %>% head()
```

### (c)
```{r}
unique(unlist(str_extract_all(sentences, "\\b[A-Za-z]{3,}s\\b"))) %>% head()

```

---

## P10 Q4
```{r}
swapped <- str_replace_all(words, "^([A-Za-z])(.*)([a-z])$", "\\3\\2\\1") 
intersect(swapped, words)
```