---
title: "章三dplyr核心操作"
author: "张平"
date: "2019年3月30日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)
library(nycflights13)
flights
```

```{r}
filter(flights, month == 1, day == 1)
```

```{r}
(dec25 <- filter(flights, month == 12, day == 25))
```
```{r}
filter(flights, month == 11 | month == 12)
filter(flights, month %in% c(11, 12))
```
```{r}
df <- tibble(x = c(1, NA, 3))
filter(df, is.na(x) | x > 1)
```
```{r}
arrange(flights, year, month, day)
arrange(flights, desc(arr_delay))
```
```{r}
df <- tibble(x = c(5, 2, NA))
#arrange(df, x)  # 缺失值总是排在最后
```

use select() to choose the columns 
```{r}
select(flights, year, month, day)
select(flights, year:day)
select(flights, -(year:day))
```
```{r}
rename(flights, tail_num = tailnum)
select(flights, time_hour, air_time, everything())
```
```{r}
flights_sml <- select(flights, 
                      year:day,
                      ends_with("delay"),
                      distance,
                      air_time)
mutate(flights_sml, 
       gain = arr_delay - dep_delay,
       speed = distance / air_time * 60
       )
flights_sml 
mutate(flights_sml, 
       gain = arr_delay - dep_delay,
       hours = air_time / 60,
       gain_per_hour = gain / hours
       )
transmute(flights, 
          gain = arr_delay - dep_delay, 
          hours = air_time / 60,
          gain_per_hour = gain / hours
          )
transmute(flights, 
          dep_time,
          hour = dep_time %/% 100,
          minute = dep_time %% 100
          )
(x <- 1:10)
lag(c)
lead(x)
```
```{r}
summarize(flights, delay = mean(dep_delay, na.rm = TRUE))
by_day <- group_by(flights, year, month, day)
summarize(by_day, delay=mean(dep_delay, na.rm = TRUE))
```
```{r}
by_dest <- group_by(flights, dest)
delay <- summarize(by_dest,
                   count = n(),
                   dist = mean(distance, na.rm = TRUE),
                   delay = mean(arr_delay, na.rm = TRUE)
                   )
delay <- filter(delay, count > 20, dest != "HNL")

ggplot(data = delay, 
       mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)

```


